version: '3'
services:
  web-server:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    depends_on:
      - website
    volumes:
      - wp:/var/www/html/sel-kham
    networks:
      - project
  database:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    env_file:
      - requirements/mariadb/.env
    restart: always
    hostname: sel-kham.42
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "-uroot", "-pHello_W0rld#YouCantH4ckMe!!:)", "ping", "--silent"]
    volumes:
      - db:/var/lib/mysql
    networks:
      - project
  website:
    container_name: wp
    build:
      context: ./requirements/WordPress
      dockerfile: ./Dockerfile
    env_file:
      - requirements/WordPress/.env
    ports:
      - "9000:9000"
    depends_on:
      database: 
        condition: service_healthy
    volumes:
      - wp:/var/www/html/sel-kham
    networks:
      - project
networks:
  project:
    driver: bridge
volumes:
  wp:
    name: wp
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wp
  db:
    name: db
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/db