services:
  database:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    env_file:
      - requirements/mariadb/.env
  # web-server:
  #   container_name: nginx
  #   build:
  #     dockerfile: ./requirements/nginx/
  #   ports:
  #     - "8080:80"
  # website:
  #   container_name: wp
  #   build:
  #     dockerfile: ./requirements/WordPress/
  
