version: '3'
services:
  web-server:
    container_name: nginx
    build:
      context: ./requirements/nginx
      dockerfile: ./Dockerfile
    ports:
      - "443:443"
    # depends_on:
    #   - website
  database:
    container_name: mariadb
    build:
      context: ./requirements/mariadb
      dockerfile: ./Dockerfile
    env_file:
      - requirements/mariadb/.env
  # website:
  #   container_name: wp
  #   build: ./requirements/WordPress
  #   dockerfile: ./Dockerfile
